#pragma once

#define NONE -1
#define CURR_STONE_CHANGE 0x01
#define LINE_COUNT 15
#define LINE_INTERVAL 48
#define BOARD_START_POINT 48
#define RESOLUTION 800
#define HALF_LINE_INTERVAL LINE_INTERVAL / 2.f
#define LINE_WIDTH 1.3f
#define STONE_RADIUS 20.0f

#define XPOS(x) (BOARD_START_POINT + (x) * LINE_INTERVAL)
#define YPOS(y) (BOARD_START_POINT + (y) * LINE_INTERVAL)

#define DELIM ","